#PBS -N BLAST2BLAST
#PBS -S /bin/bash

#PBS -l walltime=24:00:00
#PBS -l nodes=1:ppn=8
#PBS -l mem=8gb

#PBS -o /group/long-lab/Alex/CCDS/blast2blast.out
#PBS -e /group/long-lab/Alex/CCDS/blast2blast.err

module load gcc/6.2.0
module load blast/2.6.0

cd /group/long-lab/Alex/CCDS

makeblastdb -in refseq.fna -dbtype nucl -out REF

tblastx -num_threads 8 -db REF -query refseq.fna -out data -evalue 1e-6 -num_alignments 3 -outfmt "7 qseqid sseqid evalue length pident nident mismatch qframe sframe frames"
