---
title: "Analyze_frameshifts"
author: "Philipp Ross"
date: "2018-10-06"
output: workflowr::wflow_html
editor_options: 
  chunk_output_type: console
---

In order to analyze the frameshift events we've identified, we can perform gene ontology enrichment analyses and study the tissue expression of the genes.

```{r}
# Necessary libraries in order to do this analysis
library(tidyverse)
library(cowplot)
library(org.Hs.eg.db)
library(clusterProfiler)
```

## GO enrichment

### Conservative set

```{r,fig.width=10}
conservative_hits <- readr::read_tsv("../output/thirdset/conservative_reciprocal_best_hits.tsv",col_names=T)

conservative_genes <- conservative_hits$query

# we need the EntrzIDs of these genes to use enrichGO
# use the biological ID translator function for this
conservative_gene_df <- clusterProfiler::bitr(conservative_genes, fromType = "ENSEMBL",
                toType = c("ENSEMBL", "SYMBOL", "ENTREZID"),
                OrgDb = org.Hs.eg.db)

conservative_gobp <- clusterProfiler::enrichGO(
                gene          = conservative_gene_df$ENTREZID,
                OrgDb         = org.Hs.eg.db,
                ont           = "BP",
                pAdjustMethod = "BH",
                pvalueCutoff  = 0.05,
                qvalueCutoff  = 0.10)

conservative_bpcount <- tibble::tibble(GOID=conservative_gobp@result$ID,
                          `Biological Process`=conservative_gobp@result$Description,
                          `Number of genes`=conservative_gobp@result$Count,
                          Genes=conservative_gobp@result$geneID) %>%
  dplyr::arrange(desc(`Number of genes`)) %>%
  tidyr::separate(col=Genes,into=paste0(rep("gene",31),1:31),sep="/") %>%
  tidyr::gather(key=Number,value=ENTREZID,-`Biological Process`,-`Number of genes`,-GOID) %>% 
  dplyr::inner_join(conservative_gene_df) %>%
  dplyr::select(-Number)

readr::write_tsv(x=conservative_bpcount,path="../output/analyze/conservative_bpcount_table.tsv")

conservative_gomf <- clusterProfiler::enrichGO(
                 gene          = conservative_gene_df$ENTREZID,
                 OrgDb         = org.Hs.eg.db,
                 ont           = "MF",
                 pAdjustMethod = "BH",
                 pvalueCutoff  = 0.05,
                 qvalueCutoff  = 0.10)

conservative_mfcount <- tibble::tibble(GOID=conservative_gomf@result$ID,
                          `Molecular function`=conservative_gomf@result$Description,
                          `Number of genes`=conservative_gomf@result$Count,
                          Genes=conservative_gomf@result$geneID) %>%
  dplyr::arrange(desc(`Number of genes`)) %>%
  tidyr::separate(col=Genes,into=paste0(rep("gene",31),1:31),sep="/") %>%
  tidyr::gather(key=Number,value=ENTREZID,-`Molecular function`,-`Number of genes`,-GOID) %>% 
  dplyr::inner_join(conservative_gene_df) %>%
  dplyr::select(-Number)

readr::write_tsv(x=conservative_mfcount,path="../output/analyze/conservative_mfcount_table.tsv")

# Plot these enrichments
g <- clusterProfiler::dotplot(conservative_gobp,showCategory=30)
cowplot::save_plot("../output/analyze/conservative_biological_process_go_enrichment.png",plot=g,base_height=8,base_width=16)
cowplot::save_plot("../output/analyze/conservative_biological_process_go_enrichment.svg",plot=g,base_height=8,base_width=16)
print(g)

g <- clusterProfiler::dotplot(conservative_gomf,showCategory=20)
cowplot::save_plot("../output/analyze/conservative_molecular_function_go_enrichment.png",plot=g,base_height=8,base_width=16)
cowplot::save_plot("../output/analyze/conservative_molecular_function_go_enrichment.svg",plot=g,base_height=8,base_width=16)
print(g)
```

### Standard set

```{r,fig.width=10}
standard_hits <- readr::read_tsv("../output/thirdset/standard_hits.tsv",col_names=T)

standard_genes <- dplyr::union(standard_hits$query,standard_hits$subject)

# we need the EntrzIDs of these genes to use enrichGO
# use the biological ID translator function for this
standard_gene_df <- clusterProfiler::bitr(standard_genes, fromType = "ENSEMBL",
                toType = c("ENSEMBL", "SYMBOL", "ENTREZID"),
                OrgDb = org.Hs.eg.db)

standard_gobp <- clusterProfiler::enrichGO(
                gene          = standard_gene_df$ENTREZID,
                OrgDb         = org.Hs.eg.db,
                ont           = "BP",
                pAdjustMethod = "BH",
                pvalueCutoff  = 0.05,
                qvalueCutoff  = 0.10)

standard_bpcount <- tibble::tibble(GOID=standard_gobp@result$ID,
                          `Biological Process`=standard_gobp@result$Description,
                          `Number of genes`=standard_gobp@result$Count,
                          Genes=standard_gobp@result$geneID) %>%
  dplyr::arrange(desc(`Number of genes`)) %>%
  tidyr::separate(col=Genes,into=paste0(rep("gene",87),1:87),sep="/") %>%
  tidyr::gather(key=Number,value=ENTREZID,-`Biological Process`,-`Number of genes`,-GOID) %>% 
  dplyr::inner_join(standard_gene_df) %>%
  dplyr::select(-Number)

readr::write_tsv(x=standard_bpcount,path="../output/analyze/standard_bpcount_table.tsv")

standard_gomf <- clusterProfiler::enrichGO(
                 gene          = standard_gene_df$ENTREZID,
                 OrgDb         = org.Hs.eg.db,
                 ont           = "MF",
                 pAdjustMethod = "BH",
                 pvalueCutoff  = 0.05,
                 qvalueCutoff  = 0.10)

standard_mfcount <- tibble::tibble(GOID=standard_gomf @result$ID,
                          `Molecular function`=standard_gomf @result$Description,
                          `Number of genes`=standard_gomf @result$Count,
                          Genes=standard_gomf @result$geneID) %>%
  dplyr::arrange(desc(`Number of genes`)) %>%
  tidyr::separate(col=Genes,into=paste0(rep("gene",94),1:94),sep="/") %>%
  tidyr::gather(key=Number,value=ENTREZID,-`Molecular function`,-`Number of genes`,-GOID) %>% 
  dplyr::inner_join(standard_gene_df) %>%
  dplyr::select(-Number)

readr::write_tsv(x=standard_mfcount,path="../output/analyze/standard_mfcount_table.tsv")

# Plot these enrichments
g <- clusterProfiler::dotplot(standard_gobp, showCategory=30)
cowplot::save_plot("../output/analyze/standard_biological_process_go_enrichment.png",plot=g,base_height=8,base_width=16)
cowplot::save_plot("../output/analyze/standard_biological_process_go_enrichment.svg",plot=g,base_height=8,base_width=16)
print(g)

g <- clusterProfiler::dotplot(standard_gomf, showCategory=20)
cowplot::save_plot("../output/analyze/standard_molecular_function_go_enrichment.png",plot=g,base_height=8,base_width=16)
cowplot::save_plot("../output/analyze/standard_molecular_function_go_enrichment.svg",plot=g,base_height=8,base_width=16)
print(g)
```

## GTEX tissue expression analysis

### Conservative set

```{r,fig.height=8}
tpm_threshold <- 2
gtex <- readr::read_tsv("../data/GTEx_Analysis_2016-01-15_v7_RNASeQCv1.1.8_gene_median_tpm.gct",skip=2,col_names=T) %>%
  dplyr::select(-Description) %>%
  tidyr::gather(key = tissue, value = exp, -gene_id)

# remove annoying ".#" parts of each gene ID
gtex$gene_id <- sapply(stringr::str_split(gtex$gene_id,"[.]"), function(x) {x[1]})

# only include genes in our gene list
fgtex <- gtex %>% filter(gene_id %in% conservative_genes)

# group by gene ID to create histogram of how many tissues these genes are
# expressed in
gene_expression <- fgtex %>%
  dplyr::group_by(gene_id) %>%
  dplyr::summarise(n = sum(exp > tpm_threshold))

g <- ggplot(gene_expression, aes(x=n)) +
  geom_histogram(color="grey70") +
  xlab("Number of Tissues") +
  ylab("Number of Genes")

cowplot::save_plot("../output/analyze/conservative_gene_expression_distribution.png",plot=g)
cowplot::save_plot("../output/analyze/conservative_gene_expression_distribution.svg",plot=g)
print(g)

# group by tissue to create a table of how many genes are express in each
# tissue type
tissue_expression <- fgtex %>%
  dplyr::filter(exp > tpm_threshold) %>%
  dplyr::group_by(tissue) %>%
  dplyr::summarise(n = n()) %>%
  dplyr::arrange(desc(n))

g <- ggplot(tissue_expression, aes(x=reorder(tissue, n),y=n)) +
  geom_bar(stat="identity") +
  coord_flip() +
  ylab("Number of genes") +
  xlab("")

cowplot::save_plot("../output/analyze/conservative_tissue_expression_barplot.png",plot=g)
cowplot::save_plot("../output/analyze/conservative_tissue_expression_barplot.svg",plot=g)
print(g)
```

## Standard set

```{r}
# only include genes in our gene list
fgtex <- gtex %>% filter(gene_id %in% standard_genes)

# group by gene ID to create histogram of how many tissues these genes are
# expressed in
gene_expression <- fgtex %>%
  dplyr::group_by(gene_id) %>%
  dplyr::summarise(n = sum(exp > tpm_threshold))

g <- ggplot(gene_expression, aes(x=n)) +
  geom_histogram(color="grey70") +
  xlab("Number of Tissues") +
  ylab("Number of Genes")

cowplot::save_plot("../output/analyze/standard_gene_expression_distribution.png",plot=g)
cowplot::save_plot("../output/analyze/standard_gene_expression_distribution.svg",plot=g)
print(g)

# group by tissue to create a table of how many genes are express in each
# tissue type
tissue_expression <- fgtex %>%
  dplyr::filter(exp > tpm_threshold) %>%
  dplyr::group_by(tissue) %>%
  dplyr::summarise(n = n()) %>%
  dplyr::arrange(desc(n))

g <- ggplot(tissue_expression, aes(x=reorder(tissue, n),y=n)) +
  geom_bar(stat="identity") +
  coord_flip() +
  ylab("Number of genes") +
  xlab("")

cowplot::save_plot("../output/analyze/standard_tissue_expression_barplot.png",plot=g)
cowplot::save_plot("../output/analyze/standard_tissue_expression_barplot.svg",plot=g)
print(g)
```
