---
title: "Final tables"
author: "Philipp Ross"
date: "2018-11-05"
output: workflowr::wflow_html
editor_options: 
  chunk_output_type: console
---

```{r}
library(tidyverse)
library(magrittr)
library(cowplot)
library(org.Hs.eg.db)
library(clusterProfiler)
```

Code to combine previous data sets to make final tables for a manuscript.

```{r}
gtex <- readr::read_tsv("../data/GTEx_Analysis_2016-01-15_v7_RNASeQCv1.1.8_gene_median_tpm.gct",skip=2,col_names=T) %>%
  dplyr::select(-Description) %>%
  tidyr::gather(key = tissue, value = exp, -gene_id)

# remove annoying ".#" parts of each gene ID
gtex$gene_id <- sapply(stringr::str_split(gtex$gene_id,"[.]"), function(x) {x[1]})

tpm_threshold <- 2
```

## Conservative set

```{r}
cdt <- readr::read_tsv("../output/aging/conservative_data_table.tsv")

parent_genes1 <- cdt %>%
  dplyr::filter(query_relation=="parent" & subject_relation=="offspring") %$%
  query_id
parent_genes2 <- cdt %>%
  dplyr::filter(query_relation=="offspring" & subject_relation=="parent") %$%
  subject_id
parent_genes <- c(parent_genes1,parent_genes2)
rm(parent_genes1,parent_genes2)

offspring_genes1 <- cdt %>%
  dplyr::filter(query_relation=="offspring" & subject_relation=="parent") %$%
  query_id
offspring_genes2 <- cdt %>%
  dplyr::filter(query_relation=="parent" & subject_relation=="offspring") %$%
  subject_id
offspring_genes <- c(offspring_genes1,offspring_genes2)
rm(offspring_genes1,offspring_genes2)

all_genes <- c(unique(cdt$query_id,cdt$subject_id))

conservative_bptable <- readr::read_tsv("../output/analyze/conservative_bpcount_table.tsv")
conservative_bptable %>%
  dplyr::filter(ENSEMBL %in% all_genes) %>%
  dplyr::select(`Biological Process`,`Number of genes`) %>%
  dplyr::arrange(desc(`Number of genes`)) %>%
  dplyr::distinct() %>%
  readr::write_tsv("../output/final_tables/conservative_all_bp_genes.tsv")
conservative_mftable <-  readr::read_tsv("../output/analyze/conservative_mfcount_table.tsv")
conservative_mftable %>%
  dplyr::filter(ENSEMBL %in% all_genes) %>%
  dplyr::select(`Molecular function`,`Number of genes`) %>%
  dplyr::arrange(desc(`Number of genes`)) %>%
  dplyr::distinct() %>%
  readr::write_tsv("../output/final_tables/conservative_all_mf_genes.tsv")

offspring_bptable <- dplyr::filter(conservative_bptable, ENSEMBL %in% offspring_genes) %>%
  dplyr::group_by(`Biological Process`) %>%
  dplyr::summarize(n=n()) %>%
  dplyr::arrange(desc(n))
readr::write_tsv(offspring_bptable,"../output/final_tables/conservative_offspring_bptable.tsv")
parent_bptable <- dplyr::filter(conservative_bptable, ENSEMBL %in% parent_genes) %>%
  dplyr::group_by(`Biological Process`) %>%
  dplyr::summarize(n=n()) %>%
  dplyr::arrange(desc(n))
readr::write_tsv(parent_bptable,"../output/final_tables/conservative_parent_bptable.tsv")

offspring_mftable <- dplyr::filter(conservative_mftable, ENSEMBL %in% offspring_genes) %>%
  dplyr::group_by(`Molecular function`) %>%
  dplyr::summarize(n=n()) %>%
  dplyr::arrange(desc(n))
readr::write_tsv(offspring_mftable,"../output/final_tables/conservative_offspring_mftable.tsv")
parent_mftable <- dplyr::filter(conservative_mftable, ENSEMBL %in% parent_genes) %>%
  dplyr::group_by(`Molecular function`) %>%
  dplyr::summarize(n=n()) %>%
  dplyr::arrange(desc(n))
readr::write_tsv(parent_mftable,"../output/final_tables/conservative_parent_mftable.tsv")

offspring_tissues <- gtex %>%
  dplyr::filter(gene_id %in% offspring_genes) %>%
  dplyr::filter(exp > tpm_threshold) %>%
  dplyr::group_by(tissue) %>%
  dplyr::summarise(`Number of genes`=n()) %>%
  dplyr::arrange(desc(`Number of genes`))
readr::write_tsv(offspring_tissues,"../output/final_tables/conservative_offspring_tissues.tsv")
parent_tissues <- gtex %>%
  dplyr::filter(gene_id %in% parent_genes) %>%
  dplyr::filter(exp > tpm_threshold) %>%
  dplyr::group_by(tissue) %>%
  dplyr::summarise(`Number of genes`=n()) %>%
  dplyr::arrange(desc(`Number of genes`))
readr::write_tsv(parent_tissues,"../output/final_tables/conservative_parent_tissues.tsv")
all_tissues <- gtex %>%
  dplyr::filter(gene_id %in% all_genes) %>%
  dplyr::filter(exp > tpm_threshold) %>%
  dplyr::group_by(tissue) %>%
  dplyr::summarise(`Number of genes`=n()) %>%
  dplyr::arrange(desc(`Number of genes`))
readr::write_tsv(all_tissues,"../output/final_tables/conservative_all_tissues.tsv")
```

### GO analysis

After aging our genes, we can split the GO analyses by parent and offspring genes.

#### Parent genes

```{r}
parent_gene_df <- clusterProfiler::bitr(parent_genes, fromType = "ENSEMBL",
                toType = c("ENSEMBL", "SYMBOL", "ENTREZID"),
                OrgDb = org.Hs.eg.db)

parent_gobp <- clusterProfiler::enrichGO(
                gene          = parent_gene_df$ENTREZID,
                OrgDb         = org.Hs.eg.db,
                ont           = "BP",
                pAdjustMethod = "BH",
                pvalueCutoff  = 0.05,
                qvalueCutoff  = 0.10)

parent_bpcount <- tibble::tibble(GOID=parent_gobp@result$ID,
                          `Biological Process`=parent_gobp@result$Description,
                          `Number of genes`=parent_gobp@result$Count,
                          Genes=parent_gobp@result$geneID) %>%
  dplyr::arrange(desc(`Number of genes`)) %>%
  tidyr::separate(col=Genes,into=paste0(rep("gene",31),1:31),sep="/") %>%
  tidyr::gather(key=Number,value=ENTREZID,-`Biological Process`,-`Number of genes`,-GOID) %>% 
  dplyr::inner_join(parent_gene_df) %>%
  dplyr::select(-Number)

readr::write_tsv(x=parent_bpcount,path="../output/final_tables/parent_bpcount_table.tsv")

parent_gomf <- clusterProfiler::enrichGO(
                 gene          = parent_gene_df$ENTREZID,
                 OrgDb         = org.Hs.eg.db,
                 ont           = "MF",
                 pAdjustMethod = "BH",
                 pvalueCutoff  = 0.05,
                 qvalueCutoff  = 0.10)

parent_mfcount <- tibble::tibble(GOID=parent_gomf@result$ID,
                          `Molecular function`=parent_gomf@result$Description,
                          `Number of genes`=parent_gomf@result$Count,
                          Genes=parent_gomf@result$geneID) %>%
  dplyr::arrange(desc(`Number of genes`)) %>%
  tidyr::separate(col=Genes,into=paste0(rep("gene",31),1:31),sep="/") %>%
  tidyr::gather(key=Number,value=ENTREZID,-`Molecular function`,-`Number of genes`,-GOID) %>% 
  dplyr::inner_join(parent_gene_df) %>%
  dplyr::select(-Number)

readr::write_tsv(x=parent_mfcount,path="../output/final_tables/parent_mfcount_table.tsv")

# Plot these enrichments
g <- clusterProfiler::dotplot(parent_gobp,showCategory=30)
cowplot::save_plot("../output/final_tables/parent_biological_process_go_enrichment.png",plot=g,base_height=8,base_width=16)
cowplot::save_plot("../output/final_tables/parent_biological_process_go_enrichment.svg",plot=g,base_height=8,base_width=16)
print(g)

g <- clusterProfiler::dotplot(parent_gomf,showCategory=20)
cowplot::save_plot("../output/final_tables/parent_molecular_function_go_enrichment.png",plot=g,base_height=8,base_width=16)
cowplot::save_plot("../output/final_tables/parent_molecular_function_go_enrichment.svg",plot=g,base_height=8,base_width=16)
print(g)
```

#### Offspring genes

```{r}
offspring_gene_df <- clusterProfiler::bitr(offspring_genes, fromType = "ENSEMBL",
                toType = c("ENSEMBL", "SYMBOL", "ENTREZID"),
                OrgDb = org.Hs.eg.db)

offspring_gobp <- clusterProfiler::enrichGO(
                gene          = offspring_gene_df$ENTREZID,
                OrgDb         = org.Hs.eg.db,
                ont           = "BP",
                pAdjustMethod = "BH",
                pvalueCutoff  = 0.05,
                qvalueCutoff  = 0.10)

offspring_bpcount <- tibble::tibble(GOID=offspring_gobp@result$ID,
                          `Biological Process`=offspring_gobp@result$Description,
                          `Number of genes`=offspring_gobp@result$Count,
                          Genes=offspring_gobp@result$geneID) %>%
  dplyr::arrange(desc(`Number of genes`)) %>%
  tidyr::separate(col=Genes,into=paste0(rep("gene",31),1:31),sep="/") %>%
  tidyr::gather(key=Number,value=ENTREZID,-`Biological Process`,-`Number of genes`,-GOID) %>% 
  dplyr::inner_join(offspring_gene_df) %>%
  dplyr::select(-Number)

readr::write_tsv(x=offspring_bpcount,path="../output/final_tables/offspring_bpcount_table.tsv")

offspring_gomf <- clusterProfiler::enrichGO(
                 gene          = offspring_gene_df$ENTREZID,
                 OrgDb         = org.Hs.eg.db,
                 ont           = "MF",
                 pAdjustMethod = "BH",
                 pvalueCutoff  = 0.05,
                 qvalueCutoff  = 0.10)

offspring_mfcount <- tibble::tibble(GOID=offspring_gomf@result$ID,
                          `Molecular function`=offspring_gomf@result$Description,
                          `Number of genes`=offspring_gomf@result$Count,
                          Genes=offspring_gomf@result$geneID) %>%
  dplyr::arrange(desc(`Number of genes`)) %>%
  tidyr::separate(col=Genes,into=paste0(rep("gene",31),1:31),sep="/") %>%
  tidyr::gather(key=Number,value=ENTREZID,-`Molecular function`,-`Number of genes`,-GOID) %>% 
  dplyr::inner_join(offspring_gene_df) %>%
  dplyr::select(-Number)

readr::write_tsv(x=offspring_mfcount,path="../output/final_tables/offspring_mfcount_table.tsv")

# Plot these enrichments
g <- clusterProfiler::dotplot(offspring_gobp,showCategory=30)
cowplot::save_plot("../output/final_tables/offspring_biological_process_go_enrichment.png",plot=g,base_height=8,base_width=16)
cowplot::save_plot("../output/final_tables/offspring_biological_process_go_enrichment.svg",plot=g,base_height=8,base_width=16)
print(g)

g <- clusterProfiler::dotplot(offspring_gomf,showCategory=20)
cowplot::save_plot("../output/final_tables/offspring_molecular_function_go_enrichment.png",plot=g,base_height=8,base_width=16)
cowplot::save_plot("../output/final_tables/offspring_molecular_function_go_enrichment.svg",plot=g,base_height=8,base_width=16)
print(g)
```

## Standard set

```{r}
sdt <- readr::read_tsv("../output/aging/standard_data_table.tsv")

parent_genes1 <- sdt %>%
  dplyr::filter(query_relation=="parent" & subject_relation=="offspring") %$%
  query_id
parent_genes2 <- sdt %>%
  dplyr::filter(query_relation=="offspring" & subject_relation=="parent") %$%
  subject_id
parent_genes <- c(parent_genes1,parent_genes2)
rm(parent_genes1,parent_genes2)

offspring_genes1 <- sdt %>%
  dplyr::filter(query_relation=="offspring" & subject_relation=="parent") %$%
  query_id
offspring_genes2 <- sdt %>%
  dplyr::filter(query_relation=="parent" & subject_relation=="offspring") %$%
  subject_id
offspring_genes <- c(offspring_genes1,offspring_genes2)
rm(offspring_genes1,offspring_genes2)

all_genes <- c(unique(sdt$query_id,sdt$subject_id))

standard_bptable <- readr::read_tsv("../output/analyze/standard_bpcount_table.tsv")
standard_bptable %>%
  dplyr::filter(ENSEMBL %in% all_genes) %>%
  dplyr::select(`Biological Process`,`Number of genes`) %>%
  dplyr::arrange(desc(`Number of genes`)) %>%
  dplyr::distinct() %>%
  readr::write_tsv("../output/final_tables/standard_all_bp_genes.tsv")
standard_mftable <-  readr::read_tsv("../output/analyze/standard_mfcount_table.tsv")
standard_mftable %>%
  dplyr::filter(ENSEMBL %in% all_genes) %>%
  dplyr::select(`Molecular function`,`Number of genes`) %>%
  dplyr::arrange(desc(`Number of genes`)) %>%
  dplyr::distinct() %>%
  readr::write_tsv("../output/final_tables/standard_all_mf_genes.tsv")

offspring_bptable <- dplyr::filter(standard_bptable, ENSEMBL %in% offspring_genes) %>%
  dplyr::group_by(`Biological Process`) %>%
  dplyr::summarize(n=n()) %>%
  dplyr::arrange(desc(n))
readr::write_tsv(offspring_bptable,"../output/final_tables/standard_offspring_bptable.tsv")
parent_bptable <- dplyr::filter(standard_bptable, ENSEMBL %in% parent_genes) %>%
  dplyr::group_by(`Biological Process`) %>%
  dplyr::summarize(n=n()) %>%
  dplyr::arrange(desc(n))
readr::write_tsv(parent_bptable,"../output/final_tables/standard_parent_bptable.tsv")

offspring_mftable <- dplyr::filter(standard_mftable, ENSEMBL %in% offspring_genes) %>%
  dplyr::group_by(`Molecular function`) %>%
  dplyr::summarize(n=n()) %>%
  dplyr::arrange(desc(n))
readr::write_tsv(offspring_mftable,"../output/final_tables/standard_offspring_mftable.tsv")
parent_mftable <- dplyr::filter(standard_mftable, ENSEMBL %in% parent_genes) %>%
  dplyr::group_by(`Molecular function`) %>%
  dplyr::summarize(n=n()) %>%
  dplyr::arrange(desc(n))
readr::write_tsv(parent_mftable,"../output/final_tables/standard_parent_mftable.tsv")

offspring_tissues <- gtex %>%
  dplyr::filter(gene_id %in% offspring_genes) %>%
  dplyr::filter(exp > tpm_threshold) %>%
  dplyr::group_by(tissue) %>%
  dplyr::summarise(`Number of genes`=n()) %>%
  dplyr::arrange(desc(`Number of genes`))
readr::write_tsv(offspring_tissues,"../output/final_tables/standard_offspring_tissues.tsv")
parent_tissues <- gtex %>%
  dplyr::filter(gene_id %in% parent_genes) %>%
  dplyr::filter(exp > tpm_threshold) %>%
  dplyr::group_by(tissue) %>%
  dplyr::summarise(`Number of genes`=n()) %>%
  dplyr::arrange(desc(`Number of genes`))
readr::write_tsv(parent_tissues,"../output/final_tables/standard_parent_tissues.tsv")
all_tissues <- gtex %>%
  dplyr::filter(gene_id %in% all_genes) %>%
  dplyr::filter(exp > tpm_threshold) %>%
  dplyr::group_by(tissue) %>%
  dplyr::summarise(`Number of genes`=n()) %>%
  dplyr::arrange(desc(`Number of genes`))
readr::write_tsv(all_tissues,"../output/final_tables/standard_all_tissues.tsv")
```

### GO analysis

After aging our genes, we can split the GO analyses by parent and offspring genes.

#### Parent genes

```{r}
parent_gene_df <- clusterProfiler::bitr(parent_genes, fromType = "ENSEMBL",
                toType = c("ENSEMBL", "SYMBOL", "ENTREZID"),
                OrgDb = org.Hs.eg.db)

parent_gobp <- clusterProfiler::enrichGO(
                gene          = parent_gene_df$ENTREZID,
                OrgDb         = org.Hs.eg.db,
                ont           = "BP",
                pAdjustMethod = "BH",
                pvalueCutoff  = 0.05,
                qvalueCutoff  = 0.10)

parent_bpcount <- tibble::tibble(GOID=parent_gobp@result$ID,
                          `Biological Process`=parent_gobp@result$Description,
                          `Number of genes`=parent_gobp@result$Count,
                          Genes=parent_gobp@result$geneID) %>%
  dplyr::arrange(desc(`Number of genes`)) %>%
  tidyr::separate(col=Genes,into=paste0(rep("gene",31),1:31),sep="/") %>%
  tidyr::gather(key=Number,value=ENTREZID,-`Biological Process`,-`Number of genes`,-GOID) %>% 
  dplyr::inner_join(parent_gene_df) %>%
  dplyr::select(-Number)

readr::write_tsv(x=parent_bpcount,path="../output/final_tables/parent_bpcount_table.tsv")

parent_gomf <- clusterProfiler::enrichGO(
                 gene          = parent_gene_df$ENTREZID,
                 OrgDb         = org.Hs.eg.db,
                 ont           = "MF",
                 pAdjustMethod = "BH",
                 pvalueCutoff  = 0.05,
                 qvalueCutoff  = 0.10)

parent_mfcount <- tibble::tibble(GOID=parent_gomf@result$ID,
                          `Molecular function`=parent_gomf@result$Description,
                          `Number of genes`=parent_gomf@result$Count,
                          Genes=parent_gomf@result$geneID) %>%
  dplyr::arrange(desc(`Number of genes`)) %>%
  tidyr::separate(col=Genes,into=paste0(rep("gene",31),1:31),sep="/") %>%
  tidyr::gather(key=Number,value=ENTREZID,-`Molecular function`,-`Number of genes`,-GOID) %>% 
  dplyr::inner_join(parent_gene_df) %>%
  dplyr::select(-Number)

readr::write_tsv(x=parent_mfcount,path="../output/final_tables/parent_mfcount_table.tsv")

# Plot these enrichments
g <- clusterProfiler::dotplot(parent_gobp,showCategory=30)
cowplot::save_plot("../output/final_tables/parent_biological_process_go_enrichment.png",plot=g,base_height=8,base_width=16)
cowplot::save_plot("../output/final_tables/parent_biological_process_go_enrichment.svg",plot=g,base_height=8,base_width=16)
print(g)

g <- clusterProfiler::dotplot(parent_gomf,showCategory=20)
cowplot::save_plot("../output/final_tables/parent_molecular_function_go_enrichment.png",plot=g,base_height=8,base_width=16)
cowplot::save_plot("../output/final_tables/parent_molecular_function_go_enrichment.svg",plot=g,base_height=8,base_width=16)
print(g)
```

#### Offspring genes

```{r}
offspring_gene_df <- clusterProfiler::bitr(offspring_genes, fromType = "ENSEMBL",
                toType = c("ENSEMBL", "SYMBOL", "ENTREZID"),
                OrgDb = org.Hs.eg.db)

offspring_gobp <- clusterProfiler::enrichGO(
                gene          = offspring_gene_df$ENTREZID,
                OrgDb         = org.Hs.eg.db,
                ont           = "BP",
                pAdjustMethod = "BH",
                pvalueCutoff  = 0.05,
                qvalueCutoff  = 0.10)

offspring_bpcount <- tibble::tibble(GOID=offspring_gobp@result$ID,
                          `Biological Process`=offspring_gobp@result$Description,
                          `Number of genes`=offspring_gobp@result$Count,
                          Genes=offspring_gobp@result$geneID) %>%
  dplyr::arrange(desc(`Number of genes`)) %>%
  tidyr::separate(col=Genes,into=paste0(rep("gene",31),1:31),sep="/") %>%
  tidyr::gather(key=Number,value=ENTREZID,-`Biological Process`,-`Number of genes`,-GOID) %>% 
  dplyr::inner_join(offspring_gene_df) %>%
  dplyr::select(-Number)

readr::write_tsv(x=offspring_bpcount,path="../output/final_tables/offspring_bpcount_table.tsv")

offspring_gomf <- clusterProfiler::enrichGO(
                 gene          = offspring_gene_df$ENTREZID,
                 OrgDb         = org.Hs.eg.db,
                 ont           = "MF",
                 pAdjustMethod = "BH",
                 pvalueCutoff  = 0.05,
                 qvalueCutoff  = 0.10)

offspring_mfcount <- tibble::tibble(GOID=offspring_gomf@result$ID,
                          `Molecular function`=offspring_gomf@result$Description,
                          `Number of genes`=offspring_gomf@result$Count,
                          Genes=offspring_gomf@result$geneID) %>%
  dplyr::arrange(desc(`Number of genes`)) %>%
  tidyr::separate(col=Genes,into=paste0(rep("gene",31),1:31),sep="/") %>%
  tidyr::gather(key=Number,value=ENTREZID,-`Molecular function`,-`Number of genes`,-GOID) %>% 
  dplyr::inner_join(offspring_gene_df) %>%
  dplyr::select(-Number)

readr::write_tsv(x=offspring_mfcount,path="../output/final_tables/offspring_mfcount_table.tsv")

# Plot these enrichments
g <- clusterProfiler::dotplot(offspring_gobp,showCategory=30)
cowplot::save_plot("../output/final_tables/offspring_biological_process_go_enrichment.png",plot=g,base_height=8,base_width=16)
cowplot::save_plot("../output/final_tables/offspring_biological_process_go_enrichment.svg",plot=g,base_height=8,base_width=16)
print(g)

g <- clusterProfiler::dotplot(offspring_gomf,showCategory=20)
cowplot::save_plot("../output/final_tables/offspring_molecular_function_go_enrichment.png",plot=g,base_height=8,base_width=16)
cowplot::save_plot("../output/final_tables/offspring_molecular_function_go_enrichment.svg",plot=g,base_height=8,base_width=16)
print(g)
```
